apiVersion: v1
kind: ConfigMap
metadata:
  name: webnotice-toolbox-config
data:
  addr: ":9000"
  dsn: "dataset:dataset@tcp(localhost:3306)/opendataology?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conn: "100"