apiVersion: v1
kind: Service
metadata:
  name: webnotice-toolbox-service
  labels:
    app: webnotice-toolbox
spec:
  type: NodePort
  selector:
    app:  webnotice-toolbox
  ports:
    - protocol: TCP
      nodePort: 30902
      port: 9000
      targetPort: 9000
